require conf/distro/sota.conf.inc

DISTRO = "nodistro-sota"
DISTRO_NAME = "OTA-enabled Linux"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "sota"

PREFERRED_RPROVIDER_network-configuration ??= "networkd-dhcp-conf"
